<a href="https://colab.research.google.com/github/moritzfaller/Software-Entwicklung-und-Datenanalyse-in-Python/blob/main/03_Final_Result.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Final Results

In this document we conclude our work. We

## User-Input

### Background for Magic Function

In [2]:
# Install packages

!pip install spotipy
import pandas as pd
import spotipy
from spotipy.oauth2 import SpotifyClientCredentials

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import confusion_matrix

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: spotipy in /usr/local/lib/python3.7/dist-packages (2.20.0)
Requirement already satisfied: redis>=3.5.3 in /usr/local/lib/python3.7/dist-packages (from spotipy) (4.3.4)
Requirement already satisfied: requests>=2.25.0 in /usr/local/lib/python3.7/dist-packages (from spotipy) (2.28.1)
Requirement already satisfied: urllib3>=1.26.0 in /usr/local/lib/python3.7/dist-packages (from spotipy) (1.26.11)
Requirement already satisfied: six>=1.15.0 in /usr/local/lib/python3.7/dist-packages (from spotipy) (1.15.0)
Requirement already satisfied: packaging>=20.4 in /usr/local/lib/python3.7/dist-packages (from redis>=3.5.3->spotipy) (21.3)
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.7/dist-packages (from redis>=3.5.3->spotipy) (4.1.1)
Requirement already satisfied: async-timeout>=4.0.2 in /usr/local/lib/python3.7/dist-packages (from redis>=3.5.3->spotipy) (4.0.2)
Requirement already satisfied: deprecated>=1.2.3 in /usr/local/lib/python3.7/dist-packages (from redis>=3.5.3->spotipy) (1.2.13)
Requirement already satisfied: importlib-metadata>=1.0 in /usr/local/lib/python3.7/dist-packages (from redis>=3.5.3->spotipy) (4.12.0)
Requirement already satisfied: wrapt<2,>=1.10 in /usr/local/lib/python3.7/dist-packages (from deprecated>=1.2.3->redis>=3.5.3->spotipy) (1.14.1)
Requirement already satisfied: zipp>=0.5 in /usr/local/lib/python3.7/dist-packages (from importlib-metadata>=1.0->redis>=3.5.3->spotipy) (3.8.1)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /usr/local/lib/python3.7/dist-packages (from packaging>=20.4->redis>=3.5.3->spotipy) (3.0.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests>=2.25.0->spotipy) (2.10)
Requirement already satisfied: charset-normalizer<3,>=2 in /usr/local/lib/python3.7/dist-packages (from requests>=2.25.0->spotipy) (2.1.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests>=2.25.0->spotipy) (2022.6.15)

In [3]:
# Authentification

!pip install --upgrade spotipy
cid = 'ea1465c2df0a47179571e9426cd72098'
secret = 'f209c6669caa4051bff58e66407c01ac'
client_credentials_manager = SpotifyClientCredentials(client_id=cid, client_secret=secret)
sp = spotipy.Spotify(client_credentials_manager=client_credentials_manager)

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: spotipy in /usr/local/lib/python3.7/dist-packages (2.20.0)
Requirement already satisfied: six>=1.15.0 in /usr/local/lib/python3.7/dist-packages (from spotipy) (1.15.0)
Requirement already satisfied: redis>=3.5.3 in /usr/local/lib/python3.7/dist-packages (from spotipy) (4.3.4)
Requirement already satisfied: requests>=2.25.0 in /usr/local/lib/python3.7/dist-packages (from spotipy) (2.28.1)
Requirement already satisfied: urllib3>=1.26.0 in /usr/local/lib/python3.7/dist-packages (from spotipy) (1.26.11)
Requirement already satisfied: packaging>=20.4 in /usr/local/lib/python3.7/dist-packages (from redis>=3.5.3->spotipy) (21.3)
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.7/dist-packages (from redis>=3.5.3->spotipy) (4.1.1)
Requirement already satisfied: importlib-metadata>=1.0 in /usr/local/lib/python3.7/dist-packages (from redis>=3.5.3->spotipy) (4.12.0)
Requirement already satisfied: async-timeout>=4.0.2 in /usr/local/lib/python3.7/dist-packages (from redis>=3.5.3->spotipy) (4.0.2)
Requirement already satisfied: deprecated>=1.2.3 in /usr/local/lib/python3.7/dist-packages (from redis>=3.5.3->spotipy) (1.2.13)
Requirement already satisfied: wrapt<2,>=1.10 in /usr/local/lib/python3.7/dist-packages (from deprecated>=1.2.3->redis>=3.5.3->spotipy) (1.14.1)
Requirement already satisfied: zipp>=0.5 in /usr/local/lib/python3.7/dist-packages (from importlib-metadata>=1.0->redis>=3.5.3->spotipy) (3.8.1)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /usr/local/lib/python3.7/dist-packages (from packaging>=20.4->redis>=3.5.3->spotipy) (3.0.9)
Requirement already satisfied: charset-normalizer<3,>=2 in /usr/local/lib/python3.7/dist-packages (from requests>=2.25.0->spotipy) (2.1.0)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests>=2.25.0->spotipy) (2.10)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests>=2.25.0->spotipy) (2022.6.15)

In [4]:
# Creates a colab directory which is identical to github repo
!rm -rf /content/colab_files
!git clone https://github.com/jeremykleindienst/colab_files.git

# Loads dataset to variable data_full

data_full = pd.read_csv('/content/colab_files/df_model.csv')

Cloning into 'colab_files'...
remote: Enumerating objects: 6001, done.
remote: Counting objects: 100% (1803/1803), done.
remote: Compressing objects: 100% (1800/1800), done.
remote: Total 6001 (delta 3), reused 1802 (delta 3), pack-reused 4198
Receiving objects: 100% (6001/6001), 364.21 MiB | 23.37 MiB/s, done.
Resolving deltas: 100% (161/161), done.
Checking out files: 100% (2706/2706), done.

In [5]:
data_full

,danceability,energy,loudness,major,speechiness,acousticness,instrumentalness,liveness,valence,tempo,...,G,Gis,A,Ais,B,3/4,4/4,5/4,ysrelease,mood
0,0.673,0.902,-2.392,1,0.0346,0.059100,0.000262,0.0558,0.5380,100.012,...,0,0,0,0,0,0,1,0,8,happy
1,0.629,0.793,-5.942,1,0.0346,0.009520,0.000001,0.2180,0.5880,95.981,...,0,0,1,0,0,0,1,0,11,happy
2,0.388,0.338,-10.054,1,0.0329,0.652000,0.000004,0.2480,0.4780,177.765,...,0,0,0,1,0,0,1,0,45,happy
3,0.547,0.820,-6.728,1,0.0805,0.261000,0.000000,0.3000,0.9330,118.208,...,0,1,0,0,0,0,1,0,8,happy
4,0.396,0.473,-7.670,0,0.0345,0.326000,0.000124,0.1090,0.3850,133.449,...,0,0,0,1,0,0,1,0,55,happy
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3870,0.275,0.924,-3.662,0,0.0600,0.000109,0.000000,0.1220,0.3700,105.129,...,0,0,0,0,0,0,1,0,0,aggressive
3871,0.571,0.834,-4.541,1,0.0336,0.004560,0.000021,0.0879,0.5710,127.960,...,0,0,0,0,0,0,1,0,5,aggressive
3872,0.430,0.981,-2.929,1,0.0744,0.000140,0.000005,0.2870,0.5850,157.010,...,0,0,0,0,0,0,1,0,0,aggressive
3873,0.611,0.868,-3.995,0,0.0645,0.014600,0.000000,0.1220,0.4800,135.947,...,0,0,0,0,0,0,1,0,3,aggressive
3874,0.407,0.675,-6.250,1,0.0401,0.021100,0.000019,0.1060,0.0799,194.015,...,0,1,0,0,0,0,1,0,0,aggressive

In [6]:
# Perform feature scaling via standardization (z-score normalization):

metric = ['danceability', 'energy', 'loudness', 'speechiness', 'acousticness', 'instrumentalness', 'liveness', 'valence', 'tempo', 'duration_ms', 'ysrelease']
categorial = ['Cis', 'D', 'Dis', 'E', 'F', 'Fis', 'G', 'Gis', 'A', 'Ais', 'B', '3/4', '4/4', '5/4','major']

std_scaler = StandardScaler()
data_features_nonscaled_metric = data_full.loc[:,metric]
data_features_categorial = data_full.loc[:,categorial]
#data_features_nonscaled = data_full.loc[:,['energy','valence','acousticness','speechiness','ysrelease']]
data_features = std_scaler.fit_transform(data_features_nonscaled_metric)
data_features = pd.DataFrame(data_features,columns=metric)
data_features = pd.concat([data_features, data_features_categorial],axis=1)
#data_full['mood_happy'] = np.where(data_full['Mood']=='happy',1,0)
target = data_full['mood']

In [7]:
# Train and test split

X_train, X_test, y_train, y_test = train_test_split(data_features, target, test_size=0.3, random_state=24)

In [8]:
# Train model and check accuracy

gbc_classifier = GradientBoostingClassifier(random_state=24)
gbc_classifier.fit(X_train, y_train)
accuracy = gbc_classifier.score(X_test, y_test)
print(accuracy)

0.8607050730868444

In [9]:
def mood_prediction_magic(track, artist):
  track_id = sp.search(q='artist:' + artist + ' track:' + track, type='track')
  track_id = track_id['tracks']['items'][0]['id']

  track_data = sp.audio_features(track_id)
  track_data = pd.DataFrame(track_data)
  #['ysrelease'] = 2022- data_full.release_year.astype('int32')
  track_data['major'] = track_data['mode']
  a = sp.track(track_id)
  meta_release_year = int(a['album']['release_date'][0:4])
  track_data['ysrelease'] = 2022- meta_release_year

  keys = ['C','Cis','D','Dis','E','F','Fis','G','Gis','A','Ais','B']
  df_keys = pd.get_dummies(track_data.key)
  df_keys.columns = keys
  df_keys.drop(columns='C', inplace=True)

  time_signatures = ['1/4','3/4', '4/4', '5/4']
  df_time_signature = pd.get_dummies(track_data.time_signature)
  df_time_signature.columns = time_signatures
  df_time_signature.drop(columns='1/4', inplace=True)

  track_data = track_data.drop(columns=['track_href', 'type','analysis_url', 'id', 'uri', 'mode','key','time_signature'])
  
  # combining data to one data set
  data_full = pd.concat([track_data, df_keys, df_time_signature], axis=1)

  features_for_training = data_full.iloc[:,:-1]
  features_for_training = features_for_training.reindex(data_features.columns, axis=1)
  track_data = track_data.reindex(features_for_training.columns, axis=1)

  std_scaler = StandardScaler()
  scale_fit = std_scaler.fit(features_for_training) #save the mean and std. dev computed for your data.
  data_features_input = scale_fit.transform(track_data) #use the above saved values to scale your single observation or batch observations.

  data_features_input = pd.DataFrame(data_features_input)
  data_features_input.columns = track_data.columns

  label = gbc_classifier.predict(data_features_input)
  return print(label)

### Magic

In [ ]:
track= input('Enter track name here: ')
artist= input('Enter artist name here: ')

mood_prediction_magic(track, artist)

In [41]:
  track = 'Numb'
  artist = 'Linkin Park'
  track_id = sp.search(q='artist:' + artist + ' track:' + track, type='track')
  track_id = track_id['tracks']['items'][0]['id']

  track_data = sp.audio_features(track_id)
  track_data = pd.DataFrame(track_data)
  #['ysrelease'] = 2022- data_full.release_year.astype('int32')
  track_data['major'] = track_data['mode']
  a = sp.track(track_id)
  meta_release_year = int(a['album']['release_date'][0:4])
  track_data['ysrelease'] = 2022- meta_release_year

  # encoding labels

  
  from sklearn.preprocessing import LabelEncoder
  encoder = LabelEncoder()
  encoder.fit_transform(track_data.key)
  temp_key = {'1':[0],'2':[0],'3':[0],'4':[0],'5':[0],'6':[0],'7':[0],'8':[0],'9':[0],'10':[0],'11':[0],'12':[0]}
  temp_key_df = pd.DataFrame(data=temp_key)
  keys = ['C','Cis','D','Dis','E','F','Fis','G','Gis','A','Ais','B']
  df_keys = pd.get_dummies(track_data.key)
  
  temp_track_data = pd.concat([track_data, temp_key_df], axis=1)

  for i in temp_track_data.columns:
    if temp_track_data['key'][0] == i:
      #temp_track_data[i][0] = 'jsk'
      print("Yes!")
    else:
      print("Nö!")


    #if track_data['key']==x:
     # temp_key_df[x]=1
    #else:
     # pass
  #df_keys.columns = keys
  #df_keys.drop(columns='1', inplace=True)

Nö!
Nö!
Nö!
Nö!
Nö!
Nö!
Nö!
Nö!
Nö!
Nö!
Nö!
Nö!
Nö!
Nö!
Nö!
Nö!
Nö!
Nö!
Nö!
Nö!
Nö!
Nö!
Nö!
Nö!
Nö!
Nö!
Nö!
Nö!
Nö!
Nö!
Nö!
Nö!

In [44]:
temp_track_data['key'][0]

9

In [49]:
  for i in temp_track_data.columns:
    np.where(i == temp_track_data['key'][0],'test',0)

In [55]:
temp_track_data.iloc[:,15:]

,analysis_url,duration_ms,time_signature,major,ysrelease,1,2,3,4,5,6,7,8,9,10,11,12
0,https://api.spotify.com/v1/audio-analysis/2nLt...,185587,4,1,19,0,0,0,0,0,0,0,0,0,0,0,0

In [ ]:
  encoder = LabelEncoder()
  encoder.fit_transform(track_data.time_signature)
  time_signatures = ['1/4','3/4', '4/4', '5/4']
  df_time_signature = pd.get_dummies(track_data.time_signature)
  df_time_signature.columns = time_signatures
  df_time_signature.drop(columns='1/4', inplace=True)

  track_data = track_data.drop(columns=['track_href', 'type','analysis_url', 'id', 'uri', 'mode','key','time_signature'])
  
  # combining data to one data set
  data_full = pd.concat([track_data, df_keys, df_time_signature], axis=1)

  features_for_training = data_full.iloc[:,:-1]
  features_for_training = features_for_training.reindex(data_features.columns, axis=1)
  track_data = track_data.reindex(features_for_training.columns, axis=1)

  std_scaler = StandardScaler()
  scale_fit = std_scaler.fit(features_for_training) #save the mean and std. dev computed for your data.
  data_features_input = scale_fit.transform(track_data) #use the above saved values to scale your single observation or batch observations.

  data_features_input = pd.DataFrame(data_features_input)
  data_features_input.columns = track_data.columns

  label = gbc_classifier.predict(data_features_input)
  return print(label)

In [38]:
temp_track_data['9'][0] = 1

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [39]:
temp_track_data

,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,...,3,4,5,6,7,8,9,10,11,12
0,0.496,0.863,9,-4.153,1,0.0381,0.0046,0,0.639,0.243,...,0,0,0,0,0,0,1,0,0,0

In [ ]:
temp_key_df

   1  2  3  4  5  6  7  8  9  10  11  12
0  0  0  0  0  0  0  0  0  0   0   0   0

In [ ]:
df_keys

   9  9
0  1  2

In [ ]:
temp_key_df.columns

Index(['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12'], dtype='object')

In [ ]:
  temp_key = {'1':[0],'2':[0],'3':[0],'4':[0],'5':[0],'6':[0],'7':[0],'8':[0],'9':[0],'10':[0],'11':[0],'12':[0]}
  temp_key_df = pd.DataFrame(data=temp_key)

  for x in temp_key_df.columns:
    if track_data['key']==x:
      temp_key_df[x]=1
    else:
      pass
  #df_keys.columns = keys
  df_keys.drop(columns='1', inplace=True)
  df_keys

In [ ]:
  temp_key = {'1':[0],'2':[0],'3':[0],'4':[0],'5':[0],'6':[0],'7':[0],'8':[0],'9':[0],'10':[0],'11':[0],'12':[0]}
  temp_key_df = pd.DataFrame(data=temp_key)

  for x in temp_key_df.columns:
    if track_data.iloc[0,0]==x:
      temp_key_df[x]=1
    else:
      pass
  #df_keys.columns = keys
  df_keys.drop(columns='1', inplace=True)
  df_keys

In [ ]:
temp_key_df.columns

Index(['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12'], dtype='object')

In [ ]:
track_data['key'].to_frame()

   key
0    9

In [ ]:
#d = {'col1': [1, 2], 'col2': [3, 4]}

d = {'C':[0],'Cis':[0],'D':[0],'Dis':[0],'E':[0],'F':[0],'Fis':[0],'G':[0],'Gis':[0],'A':[0],'Ais':[0],'B':[0]}
d2 = {'1':[0],'2':[0],'3':[0],'4':[0],'5':[0],'6':[0],'7':[0],'8':[0],'9':[0],'10':[0],'11':[0],'12':[0]}
df = pd.DataFrame(data=d2)
df

   1  2  3  4  5  6  7  8  9  10  11  12
0  0  0  0  0  0  0  0  0  0   0   0   0

In [ ]:
track_data

,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,type,id,uri,track_href,analysis_url,duration_ms,time_signature,major,ysrelease
0,0.496,0.863,9,-4.153,1,0.0381,0.0046,0,0.639,0.243,110.018,audio_features,2nLtzopw4rPReszdYBJU6h,spotify:track:2nLtzopw4rPReszdYBJU6h,https://api.spotify.com/v1/tracks/2nLtzopw4rPR...,https://api.spotify.com/v1/audio-analysis/2nLt...,185587,4,1,19

In [ ]:
df_keys

   9  9
0  1  2

In [ ]:
df_keys['9']=2

## Overview of different Models

In [ ]:
#

*kursiver Text*## Final Model

In [ ]:
#

## Final Thoughts

In [ ]:
#